import ProjectStore from './instance';

class ProjectLocalStore {
  _instance: ProjectStore = new ProjectStore();
  _onInstanceUnmount: () => void = () => {};

  async initialize() {
    global.master.services.ipc.on('projectStoreService.initProjectStore', async (params) => {
      console.log('[projectStoreService] init project store, params is', params);
      await this.initProjectStore(params);
    });
    global.master.services.ipc.on('projectStoreService.unmountProjectStore', async (params) => {
      console.log('[projectStoreService] unmount project store, params is', params);
      this._onInstanceUnmount();
      return null;
    });
    return this._instance;
  }

  /**
   * @description 初始化一份工程
   */
  async initProjectStore(params: any) {
    console.log('[projectStoreService] a project file will be created and stored locally, which holds all the datasets generated by recording clips');
    console.log('[projectStoreService] created params is', params);
  }
}

export default new ProjectLocalStore();