import { EResourceType } from '@typings/resource/enum';
import path from 'path';

const cloudAudioFilePath = `${window?.master?.appRootPath || ''}\\src\\assets\\cloudResource\\audio`;

const CLOUD_RESOURCE_AUDIO_LIST: MasterResourceType.IAudioResource[] = [
  {
    uid: 'cloud.audio.resource.001',
    cloudRemoteUid: 'cloud.audio.resource.001',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '名侦探柯南的音效铃声.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\名侦探柯南的音效铃声.mp3'),
    cover: '',
    data: {
      duration: 14,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.002',
    cloudRemoteUid: 'cloud.audio.resource.002',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '大话西游出场音效.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\大话西游出场音效.mp3'),
    cover: '',
    data: {
      duration: 37,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.003',
    cloudRemoteUid: 'cloud.audio.resource.003',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '快节奏动感音效.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: '',
    cover: '',
    data: {
      duration: 23,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.004',
    cloudRemoteUid: 'cloud.audio.resource.004',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '热门世界杯BGM.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\热门世界杯BGM.mp3'),
    cover: '',
    data: {
      duration: 8,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.005',
    cloudRemoteUid: 'cloud.audio.resource.005',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '热曲带我去找夜生活.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\热曲带我去找夜生活.mp3'),
    cover: '',
    data: {
      duration: 38,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.006',
    cloudRemoteUid: 'cloud.audio.resource.006',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '世界杯心墙DJ.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\世界杯心墙DJ.mp3'),
    cover: '',
    data: {
      duration: 120,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.007',
    cloudRemoteUid: 'cloud.audio.resource.007',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '热曲给你一瓶魔法药水.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\热曲给你一瓶魔法药水.mp3'),
    cover: '',
    data: {
      duration: 26,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.008',
    cloudRemoteUid: 'cloud.audio.resource.008',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '短视频爆火卡点神曲BGM.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\短视频爆火卡点神曲BGM.mp3'),
    cover: '',
    data: {
      duration: 26,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.009',
    cloudRemoteUid: 'cloud.audio.resource.009',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '节奏开场.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\节奏开场.mp3'),
    cover: '',
    data: {
      duration: 10,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.010',
    cloudRemoteUid: 'cloud.audio.resource.010',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '观众哄笑抽气音效.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\观众哄笑抽气音效.mp3'),
    cover: '',
    data: {
      duration: 5,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.011',
    cloudRemoteUid: 'cloud.audio.resource.011',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '轻松的搞笑氛围音.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\轻松的搞笑氛围音.mp3'),
    cover: '',
    data: {
      duration: 10,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
  {
    uid: 'cloud.audio.resource.012',
    cloudRemoteUid: 'cloud.audio.resource.012',
    cloudRemoteUrl: '',
    type: EResourceType.audio,
    size: 307686,
    name: '非诚勿扰连续灭灯.mp3',
    visible: true,
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudAudioFilePath, '\\非诚勿扰连续灭灯.mp3'),
    cover: '',
    data: {
      duration: 8,
      bit_rate: 0,
      codec_name: 'aac',
      sample_rate: 0,
      avg_frame_rate: '14/s',
    },
  },
];

export default CLOUD_RESOURCE_AUDIO_LIST;
