import { EResourceType } from '@typings/resource/enum';
import path from 'path';

const cloudImageFilePath = `${window?.master?.appRootPath || ''}\\src\\assets\\material\\image`;

const CLOUD_RESOURCE_IMAGE_LIST: MasterResourceType.IImageResource[] = [
  {
    uid: 'cloud.image.resource.001',
    type: EResourceType.image,
    size: 307686,
    name: '升级.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\升级.png'),
    cover: path.join(cloudImageFilePath, '\\升级.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.002',
    type: EResourceType.image,
    size: 307686,
    name: '麦克风.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\麦克风.png'),
    cover: path.join(cloudImageFilePath, '\\麦克风.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.003',
    type: EResourceType.image,
    size: 307686,
    name: '猫猫贴纸.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\猫猫贴纸.png'),
    cover: path.join(cloudImageFilePath, '\\猫猫贴纸.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.004',
    type: EResourceType.image,
    size: 307686,
    name: '爱心咖啡.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\爱心咖啡.png'),
    cover: path.join(cloudImageFilePath, '\\爱心咖啡.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.005',
    type: EResourceType.image,
    size: 307686,
    name: '尽请期待.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\尽请期待.png'),
    cover: path.join(cloudImageFilePath, '\\尽请期待.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.006',
    type: EResourceType.image,
    size: 307686,
    name: '推荐好友.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\推荐好友.png'),
    cover: path.join(cloudImageFilePath, '\\推荐好友.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.007',
    type: EResourceType.image,
    size: 307686,
    name: '比心.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\比心.png'),
    cover: path.join(cloudImageFilePath, '\\比心.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.008',
    type: EResourceType.image,
    size: 307686,
    name: '敬请期待.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\敬请期待.png'),
    cover: path.join(cloudImageFilePath, '\\敬请期待.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.009',
    type: EResourceType.image,
    size: 307686,
    name: '猜你喜欢.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\猜你喜欢.png'),
    cover: path.join(cloudImageFilePath, '\\猜你喜欢.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.010',
    type: EResourceType.image,
    size: 307686,
    name: '推荐.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\推荐.png'),
    cover: path.join(cloudImageFilePath, '\\推荐.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.011',
    type: EResourceType.image,
    size: 307686,
    name: '先享后付.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\先享后付.png'),
    cover: path.join(cloudImageFilePath, '\\先享后付.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.012',
    type: EResourceType.image,
    size: 307686,
    name: '好评.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\好评.png'),
    cover: path.join(cloudImageFilePath, '\\好评.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.013',
    type: EResourceType.image,
    size: 307686,
    name: '可爱猫猫.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\可爱猫猫.png'),
    cover: path.join(cloudImageFilePath, '\\可爱猫猫.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.014',
    type: EResourceType.image,
    size: 307686,
    name: '蜜蜂小可爱.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\蜜蜂小可爱.png'),
    cover: path.join(cloudImageFilePath, '\\蜜蜂小可爱.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.015',
    type: EResourceType.image,
    size: 307686,
    name: '大喇叭.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\大喇叭.png'),
    cover: path.join(cloudImageFilePath, '\\大喇叭.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.016',
    type: EResourceType.image,
    size: 307686,
    name: '万圣节.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\万圣节.png'),
    cover: path.join(cloudImageFilePath, '\\万圣节.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.017',
    type: EResourceType.image,
    size: 307686,
    name: '外卖车.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\外卖车.png'),
    cover: path.join(cloudImageFilePath, '\\外卖车.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.018',
    type: EResourceType.image,
    size: 307686,
    name: '外卖配送中.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\外卖配送中.png'),
    cover: path.join(cloudImageFilePath, '\\外卖配送中.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.019',
    type: EResourceType.image,
    size: 307686,
    name: '禁止攀爬.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\禁止攀爬.png'),
    cover: path.join(cloudImageFilePath, '\\禁止攀爬.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.020',
    type: EResourceType.image,
    size: 307686,
    name: '禁止吸烟.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\禁止吸烟.png'),
    cover: path.join(cloudImageFilePath, '\\禁止吸烟.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.021',
    type: EResourceType.image,
    size: 307686,
    name: '香蕉.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\香蕉.png'),
    cover: path.join(cloudImageFilePath, '\\香蕉.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.022',
    type: EResourceType.image,
    size: 307686,
    name: '饼干.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\饼干.png'),
    cover: path.join(cloudImageFilePath, '\\饼干.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.023',
    type: EResourceType.image,
    size: 307686,
    name: '狗狗.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\狗狗.png'),
    cover: path.join(cloudImageFilePath, '\\狗狗.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.024',
    type: EResourceType.image,
    size: 307686,
    name: '狗头.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\狗头.png'),
    cover: path.join(cloudImageFilePath, '\\狗头.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.025',
    type: EResourceType.image,
    size: 307686,
    name: '圣诞帽.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\圣诞帽.png'),
    cover: path.join(cloudImageFilePath, '\\圣诞帽.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
  {
    uid: 'cloud.image.resource.026',
    type: EResourceType.image,
    size: 307686,
    name: '鼓掌.png',
    createTime: 1691142324878,
    updateTime: 1691142324878,
    isExistResource: true,
    inputPath: path.join(cloudImageFilePath, '\\鼓掌.png'),
    cover: path.join(cloudImageFilePath, '\\鼓掌.png'),
    data: {
      resolutionHeight: 100,
      resolutionWidth: 200,
      pointer: {
        x: 0,
        y: 0,
        offsetWidth: 118,
        offsetHeight: 118,
        scale: 1,
      },
    },
  },
];

export default CLOUD_RESOURCE_IMAGE_LIST;
